### ISSUE TITLE
env

### ISSUE THREAD

**Issue by ghost** [czim/laravel-cms-example#1]
why did you delete the .env file ?

**Comment by czim** [comment]
I figured it would be too specific, and would need to be tailored for everyone's environment anyway.

There is a basic .env example in the readme. Would it be better if I (re-)added this as .env.example?

**Comment by czim** [comment]
I have added the normal `.env.example` file back in. I've also added a docker setup (`docker-compose.yml` and `Makefile`) to facilitate a quicker/easier setup.
