### ISSUE TITLE
Docker approach is broken for newest Laravel version

### ISSUE THREAD

**Issue by czim** [czim/laravel-cms-example#2]
Looks like the nginx + php container does not sport a recent enough PHP version. Probably best to switch to a standard Apache-based image anyway.

**Comment by nick-sturrock** [comment]
Is this related to getting an error during make with the following output? Or am I doing something else wrong here?

`Setting up docker...
docker-compose up -d --force-recreate --remove-orphans
Recreating laravel-cms-example_redis_1 ... done
Recreating laravel-cms-example_mysql_1 ... done
Recreating laravel-cms-example_app_1   ... done
=> Preparing environment...
cp .env.docker .env && \
		docker-compose exec app bash -c 'php artisan key:generate; (exit )'

Warning: require(/var/www/html/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/bootstrap/autoload.php on line 17

Fatal error: require(): Failed opening required '/var/www/html/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/bootstrap/autoload.php on line 17
make: *** [env] Error 255`

**Comment by czim** [comment]
Looks like you skipped the `composer install` step? Otherwise there really should be a vendor/autoload. Can you check if the composer install worked without issues?

**Comment by nick-sturrock** [comment]
Yes, that’s the conclusion I also came to, but I can’t see the composer install step in the Dockerfile - shouldn’t it be run inside the container rather than needing to run it manually prior to the build step?

Anyway have run prior to make and it now builds correctly - thanks for your help!

**Comment by czim** [comment]
Running it in the container requires having composer installed in the container. If you want to make your custom setup where this is possible, that should be absolutely fine.

If not, your best bet is to run it outside of the container -- or create a separate composer container and run the install in there.

Good luck!
